import type { UseCaseModule } from "@/app/types";

export const realtimeVoiceUseCase: UseCaseModule = {
  id: "realtime_voice",
  title: "Realtime Speech in / Speech out",
  shortTitle: "Realtime",
  description:
    "Stream microphone audio to a realtime deployment and play the audio response.",
  badge: "WebRTC",
  icon: "voiceWave",
  modalities: ["audio"],
  implementation: [
    "The frontend asks the backend for a short-lived Foundry Realtime client secret.",
    "The browser opens a WebRTC peer connection, sends the local microphone track, and posts the SDP offer to Foundry Realtime.",
    "Foundry returns audio on the remote media track and sends transcript/events over the data channel.",
  ],
  codeSnippet: {
    title: "Foundry Realtime: mint a client secret",
    language: "python",
    code: [
      "endpoint = _normalize_realtime_endpoint(settings.realtime_endpoint or '')",
      "token_url = f'{endpoint}/realtime/client_secrets'",
      "payload = {",
      "    'session': {",
      "        'type': 'realtime',",
      "        'model': settings.realtime_model,",
      "        'instructions': instructions.strip(),",
      "        'output_modalities': ['audio'],",
      "        'audio': {",
      "            'input': {'transcription': {'model': 'whisper-1'}},",
      "            'output': {'voice': voice.strip() or 'alloy'},",
      "        },",
      "    }",
      "}",
      "",
      "with DefaultAzureCredential() as credential:",
      "    bearer_token = credential.get_token('https://ai.azure.com/.default').token",
      "",
      "request = Request(token_url, data=json.dumps(payload).encode('utf-8'), headers={",
      "    'Authorization': f'Bearer {bearer_token}',",
      "    'Content-Type': 'application/json',",
      "}, method='POST')",
      "with urlopen(request, timeout=30) as response:",
      "    data = json.loads(response.read().decode('utf-8'))",
      "client_secret = data.get('value') or data.get('client_secret', {}).get('value')",
    ].join("\n"),
  },
  workspace: "realtimeVoice",
};
