import type { UseCaseModule } from "@/app/types";

export const traditionalVoiceUseCase: UseCaseModule = {
  id: "traditional_voice",
  title: "STT -> Chat -> TTS",
  shortTitle: "STT -> TTS",
  description: "Record audio, transcribe it in Foundry, ask the chat model, then synthesize speech.",
  badge: "Foundry audio",
  icon: "voiceWave",
  implementation: [
    "The browser records microphone audio with MediaRecorder and uploads the audio blob to the backend.",
    "The backend calls Foundry `/audio/transcriptions`, sends the transcript to the selected chat model, then calls `/audio/speech`.",
    "The response includes transcript text, assistant text, timing metadata, and base64 MP3 audio for playback in the browser.",
  ],
  codeSnippet: {
    title: "Foundry SDK: STT, chat, and TTS",
    language: "python",
    code: [
      "with _create_openai_client(settings) as openai_client:",
      "    transcription = openai_client.audio.transcriptions.create(",
      "        model=settings.transcription_model,",
      "        file=audio_file,",
      "    )",
      "",
      "chat_response = complete_chat(",
      "    model=model,",
      "    prompt=transcription.text.strip(),",
      "    api_surface=model_settings.api_surface,",
      "    system_prompt=model_settings.system_prompt,",
      "    temperature=model_settings.temperature,",
      "    top_p=model_settings.top_p,",
      "    max_tokens=model_settings.max_tokens,",
      ")",
      "",
      "with _create_openai_client(settings) as openai_client:",
      "    speech = openai_client.audio.speech.create(",
      "        model=settings.tts_model,",
      "        voice=settings.tts_voice,",
      "        input=chat_response['content'],",
      "        response_format='mp3',",
      "    )",
    ].join("\n"),
  },
  workspace: "traditionalVoice",
};
