from collections.abc import Iterator
from typing import Any, Protocol


class FoundryChatGateway(Protocol):
    def build_request_trace(self, **kwargs: Any) -> dict[str, Any]: ...
    def complete(self, **kwargs: Any) -> dict[str, Any]: ...
    def stream(self, **kwargs: Any) -> Iterator[dict[str, Any]]: ...
