from typing import Protocol, runtime_checkable

from app.domain.models import ModelSettings


@runtime_checkable
class ModelSettingsRepository(Protocol):
    def list_models(self) -> list[str]: ...
    def get_settings(self, model: str) -> ModelSettings | None: ...
    def add_settings_if_absent(self, settings: ModelSettings) -> None: ...
    def save_settings(self, settings: ModelSettings) -> None: ...
